/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Database {
  constructor(path: string)
  execute(sql: string): void
  query(sql: string): Array<object>
  table(name: string): Table
}
export declare class Table {
  find(id: number | string): object | null
  get(): Array<object>
  all(): Array<object>
  where(column: string, opOrValue: string | string | number, valueOpt?: string | number | undefined | null): FilteredTable
  insert(data: unknown): void
  create(data: unknown): void
  update(id: string | number, data: object): void
  orderBy(column: string, direction?: string | undefined | null): FilteredTable
  destroy(id: string | number): void
}
export declare class FilteredTable {
  first(): object | null
  last(): object | null
  orderBy(column: string, direction?: string | undefined | null): FilteredTable
  where(column: string, opOrValue: string | string | number, valueOpt?: string | number | undefined | null): FilteredTable
  get(): Array<object>
  all(): Array<object>
  update(data: object): void
  set destroy()
}
