name: Build Native Universal

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-arm64-gnu
          - os: ubuntu-latest
            target: linux-x64-gnu
          - os: ubuntu-latest
            target: linux-x64-musl
          - os: ubuntu-latest
            target: linux-aarch64-gnu
          - os: ubuntu-latest
            target: linux-aarch64-musl
          - os: ubuntu-latest
            target: linux-aarch64-android
          - os: ubuntu-latest
            target: linux-armv7-android
          - os: windows-latest
            target: win32-x64-msvc

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --global @napi-rs/cli

      - name: Build napi binary
        run: napi build --platform --release

      - name: Rename and store .node file
        run: |
          mkdir -p artifact
          mv ./native/*.node artifact/rustite.${{ matrix.target }}.node

      - uses: actions/upload-artifact@v4
        with:
          name: rustite-${{ matrix.target }}
          path: artifact/rustite.${{ matrix.target }}.node

  make-universal:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (again)
        run: npm install --global @napi-rs/cli

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: native

      - name: Flatten native dir
        run: |
          mkdir flat
          find native -type f -name "*.node" -exec mv {} flat/ \;
          rm -rf native
          mv flat native

      - name: Run napi universal
        run: |
          mkdir -p native-universal
          napi universal --dir native --dist native-universal

      - name: Commit and push universal binary
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add native-universal/
          git commit -m "chore: add universal binary [skip ci]" || echo "No changes"
          git push
  