name: Build & Upload Prebuild

on:
  push:
    branches: [ "main" ]
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install napi cli
        run: npm install --global @napi-rs/cli

      - name: Install dependencies
        run: npm install

      - name: Build prebuild
        run: npm run prebuild

      - name: Upload prebuild to GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TAG_NAME="${{ github.ref_name }}"
          if [[ -z "$TAG_NAME" || "$TAG_NAME" == "main" ]]; then
            TAG_NAME="latest"
          fi
          gh release upload "$TAG_NAME" native/**/*
